# Generated by Django 4.2 on 2023-04-21 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
                ('pwd', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='user_model_extended',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tour', models.CharField(max_length=100)),
                ('numero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user_model')),
            ],
        ),
    ]
