# Generated by Django 4.2 on 2023-04-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_model_extended',
            name='name',
        ),
        migrations.AddField(
            model_name='user_model',
            name='tour',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
