# Generated by Django 4.2 on 2023-04-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_user_model_extended_name_user_model_tour'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_model',
            name='name',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
