# Generated by Django 4.2 on 2023-04-21 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_model_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_model',
            name='tour',
        ),
    ]
