# Generated by Django 4.2 on 2023-04-21 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_user_model_tour'),
    ]

    operations = [
        migrations.CreateModel(
            name='tour_user_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user_model')),
            ],
        ),
        migrations.DeleteModel(
            name='user_model_extended',
        ),
    ]
