# Generated by Django 4.2 on 2023-04-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_tour_user_model_delete_user_model_extended'),
    ]

    operations = [
        migrations.CreateModel(
            name='Box_tours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tour', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
    ]
