# Generated by Django 4.2 on 2023-04-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_box_tours'),
    ]

    operations = [
        migrations.AddField(
            model_name='box_tours',
            name='fecha',
            field=models.CharField(default=None, max_length=40),
        ),
    ]
