# Generated by Django 4.2 on 2023-04-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_box_tours_fecha_box_tours_fechas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box_tours',
            name='fechas',
        ),
        migrations.AddField(
            model_name='box_tours',
            name='dia',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
