# Generated by Django 4.2 on 2023-04-25 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_user_facebook_alter_user_gmail_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
