# Generated by Django 4.2 on 2023-04-26 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_tour_user_model_user_alter_user_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='box_tours',
            name='code_paquet',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='box_tours',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='box_tours',
            name='value_cu',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
