# Generated by Django 4.2 on 2023-04-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_box_tours_code_paquet_box_tours_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='box_tours',
            name='buy_getting',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='box_tours',
            name='reserved_getting',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
