# Generated by Django 4.2 on 2023-04-27 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_box_tours_buy_getting_box_tours_reserved_getting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour_user_model',
            name='tour',
        ),
        migrations.AddField(
            model_name='tour_user_model',
            name='number_id_tour',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
