# Generated by Django 4.2 on 2023-04-27 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_tour_user_model_tour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour_user_model',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
