# Generated by Django 4.2 on 2023-04-28 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_tour_user_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='box_tours',
            name='cupos',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
