# Generated by Django 4.2 on 2023-04-28 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_box_tours_cupos'),
    ]

    operations = [
        migrations.AddField(
            model_name='box_tours',
            name='limites',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
