# Generated by Django 4.2 on 2023-04-28 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_box_tours_limites'),
    ]

    operations = [
        migrations.CreateModel(
            name='Get_buy_tours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tour', models.CharField(max_length=100)),
                ('box_tours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.box_tours')),
            ],
        ),
    ]
