# Generated by Django 4.2 on 2023-04-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_get_buy_tours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='get_buy_tours',
            name='name_tour',
        ),
        migrations.AddField(
            model_name='get_buy_tours',
            name='number_get_buy',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
