# Generated by Django 4.2 on 2023-05-02 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_faq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box_tours',
            name='cupos',
        ),
        migrations.AddField(
            model_name='box_tours',
            name='asientos',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
