# Generated by Django 4.2 on 2023-05-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_remove_box_tours_cupos_box_tours_asientos'),
    ]

    operations = [
        migrations.AddField(
            model_name='box_tours',
            name='photo1_s',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='box_tours',
            name='photo2_s',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='box_tours',
            name='photo3_s',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='box_tours',
            name='photo4_s',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
