# Generated by Django 4.2 on 2023-05-11 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_box_tours_photo1_s_box_tours_photo2_s_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='instagram',
        ),
        migrations.AddField(
            model_name='user',
            name='g',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
