# Generated by Django 4.2 on 2023-05-11 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_remove_user_instagram_user_g'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='g',
        ),
        migrations.AddField(
            model_name='user',
            name='instagram',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
