# Generated by Django 4.2 on 2023-05-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_remove_user_g_user_instagram'),
    ]

    operations = [
        migrations.CreateModel(
            name='WellcomeStart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_img', models.CharField(max_length=100)),
                ('photo_welcome', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
