# Generated by Django 4.2 on 2023-05-11 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_wellcomestart_photo1_s_wellcomestart_photo2_s_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wellcomestart',
            old_name='photo1_s',
            new_name='photo_welcome_dos',
        ),
        migrations.RenameField(
            model_name='wellcomestart',
            old_name='photo2_s',
            new_name='photo_welcome_tres',
        ),
        migrations.RenameField(
            model_name='wellcomestart',
            old_name='photo3_s',
            new_name='photo_welcome_uno',
        ),
        migrations.RemoveField(
            model_name='wellcomestart',
            name='photo4_s',
        ),
    ]
